version: 2
jobs:
  build_be:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Clean install
          command: mvn clean install -DskipTests=true
      - run:
          name: Run tests
          command: mvn verify -B -P integration-test --fail-at-end
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/junit/ \;
            find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit
  build_admin:
    working_directory: ~/repo/admin

    docker:
      - image: circleci/node:6-browsers

    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - ./node_modules
      - run:
          name: angular-build
          command: yarn ng -- build --prod --aot --no-progress
      - run:
          name: angular-test
          command: yarn test -- --single-run --no-progress
      - store_artifacts:
          path: test-results.xml
          prefix: tests
      - run:
          name: angular-e2e
          command: yarn e2e
      - store_artifacts:
          path: e2e/junitresults.xml
          prefix: e2e
      - run:
          name: angular-lint
          command: yarn lint --format stylish
workflows:
  version: 2
  pipeline:
    jobs:
      - build_be
      - build_admin