spring:
  data:
    mongodb:
      host: ds121299.mlab.com
      port: 21299
      database: letitroll
      username: admin
      password: YeJqDDmHR7Hp
  jackson:
    time-zone: UTC

mongobee:
  changelog-package: io.letitroll.be.persistence.changelog
